REMOTE_URL:
- file:///opt/spaceone/inventory/config/database.yaml
- file:///opt/spaceone/inventory/config/shared.yaml
- file:///opt/spaceone/inventory/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  DATABASES:
    default:
      db: inventory
      host: mongodb
      port: 27017
      maxPoolSize: 200
      username: inventory_user
      password: inventory_password
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/inventory.log
  QUEUES:
      collector_q:
        backend: spaceone.core.queue.redis_queue.RedisQueue
        host: redis
        port: 6379
        channel: collector

  collect_queue: collector_q
